export const Stages = {
  NOVO: "C9:NEW",
  SOLICITAR_PAGAMENTO: "C9:PREPARATION",
  ERRO_SOLICITANDO_PAGAMENTO: "C9:PREPAYMENT_INVOICE",
  AGUARDANDO_PAGAMENTO: "C9:EXECUTING",
  FIM_CONTA_SECUNDARIA: "C9:UC_0H0Q8A",
  GERAR_NOTA_FISCAL: "C9:UC_LYDAX1",
  ERRO_GERANDO_NOTA_FISCAL: "C9:UC_C1T4PT",
  NOTA_AGUARDANDO_APROVACAO: "C9:UC_S0GGXP",
  FIM: "C9:FINAL_INVOICE",
};
